Parcial1_DPWA/Models/BaseModel.cs
namespace Parcial1_DPWA.Models
{
    public class BaseModel
    {
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public DateTime Created { get; set; }
        public string? EditedBy { get; set; }
        public DateTime? Edited { get; set; }
    }
}

Parcial1_DPWA/Models/ErrorViewModel.cs
namespace Parcial1_DPWA.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Parcial1_DPWA/Models/Faculties.cs
using System.ComponentModel.DataAnnotations;

namespace Parcial1_DPWA.Models
{
    public class Faculties : BaseModel
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        [Required]
        public string Correo { get; set; }
        [Required]
        public string Description { get; set; }
        public int CantidadCarreras { get; set; }
        public bool IsActive { get; set; }
        #region  Constructor
        public Faculties()
        {
            IsActive = true;
            Created = DateTime.Now;

        }
        public Faculties(string name, string correo, string description, int cantidadmaterias)
        {
            Name = name;
            Correo = correo;
            Description = description;
            CantidadCarreras = cantidadmaterias;
        }
        #endregion Constructor
        #region  Funcion

        public void ToggleStatus()
        {
            IsActive = !IsActive; // Cambia el estado actual (true/false)
        }
        #endregion Funcion
    }

}

Parcial1_DPWA/Controllers/FacultiesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Parcial1_DPWA.Db;
using Parcial1_DPWA.Models;

namespace Parcial1_DPWA.Controllers
{
    public class FacultiesController : Controller
    {
        private readonly AppDbContext _dbConn;

        public FacultiesController(AppDbContext appDb)
        {
            _dbConn = appDb;
        }

        // Mostrar todas las facultades
        public IActionResult Index()
        {
            List<Faculties> faculties = _dbConn.Faculties.ToList();
            return View(faculties);
        }
        public IActionResult UpSert(int id)
        {
            if (id == 0)
            {
                //REGISTRO NUEVO
                Faculties faculties = new();
                return View(faculties);
            }
            else
            {
                //REGISTRO EXISTENTE
                Faculties faculties = _dbConn.Faculties.FirstOrDefault(row => row.Id == id) ?? new();
                return View(faculties);
            }
        }
        [HttpPost]
        public IActionResult UpSert(Faculties model)
        {
            if (model.Id == 0)
            {
                if (ModelState.IsValid)
                {
                    _dbConn.Faculties.Add(model);
                    _dbConn.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            else
            {
                if (ModelState.IsValid)
                {
                    _dbConn.Faculties.Update(model);
                    _dbConn.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Faculties faculties = _dbConn.Faculties.FirstOrDefault(row => row.Id == id) ?? new();
            faculties.IsActive = false;
            _dbConn.Faculties.Update(faculties);
            _dbConn.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Parcial1_DPWA/Views/Faculties/Create.cshtml
@model Faculties;

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="breadcrumb-item">
            <a asp-controller="Faculties" asp-action="Index">Index</a>
        </li>
        <li class="breadcrumb-item">Agregar nuevo registro</li>
    </ol>
</nav>

<form asp-action="Create" asp-controller="Faculties" method="POST">
    <div asp-validation-summary="All" class="alert alert-danger">
        <i class="bi bi-exclamation-triangle-fill"></i>
    </div>
    <input type="hidden" asp-for="Id" value="@Model.Id" placeholder="Id" aria-label="Id">


    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1">
            <span class="fas fa-user"></span>
        </span>
        <input type="text" class="form-control" asp-for="Name" placeholder="Name" aria-label="Nombre">
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1"><span class="fas fa-user"></span></span>
        <input type="text" class="form-control" asp-for="Correo" placeholder="Correo" aria-label="Correo">
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1"><span class="fas fa-user"></span></span>
        <input type="text" class="form-control" asp-for="Description" placeholder="Description" aria-label="Descripccion">
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1"><span class="fas fa-hashtag"></span></span>
        <input type="number" class="form-control" asp-for="CantidadCarreras" value="@((Model.CantidadCarreras == 0) ? string.Empty : Model.CantidadCarreras)" placeholder="Cantidad de Carreras" aria-label="CantidadCarreras">
    </div>
    <div class="mb-3">
        <label asp-for="CreatedBy" class="form-label">Creado por</label>
        <input asp-for="CreatedBy" class="form-control" />
        <span asp-validation-for="CreatedBy" class="text-danger"></span>
    </div>
    <button class="btn btn-success" type="submit"><span class="fas fade save"></span>Guardar Informacion</button>
</form>

Parcial1_DPWA/Views/Faculties/Index.cshtml
@model List<Faculties>
<nav aria-label="breadcrumb">
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a asp-controller="Home" asp-action="Index">Home</a>
		</li>
		<li class="breadcrumb-item">Index</li>
	</ol>
</nav>
<div class=" container">
    <div class="row">
		<div class="col-xl-12 col-md-12 col-sm-12 d-flex justify-content-start">
			<a type="button" class="btn btn-primary" asp-action="UpSert" asp-controller="Faculties"><span class="fas fa-plus"></span> Agregar Facultad</a>
		</div>
		<div class="col-xl-12 col-md-12 col-sm-12 mt-3"> 
			<table class="table table-striped table-bordered table-hover shadow-sm">
				<thead thead-dark>
					<tr>
						<th>Id</th>
						<th>Nombre</th>
						<th>Correo</th>
						<th>Descripción</th>
						<th>Estado</th>
						<th>Acciones</th>
					</tr>
					</thead>
				<tbody>
					@{
						foreach (Faculties faculties in Model)
						{
							<tr>
								<td>@faculties.Id</td>
								<td>@faculties.Name</td>
								<td>@faculties.Correo</td>
								<td>@faculties.Description</td>
								<td>
								    @if (faculties.IsActive)
								    {
									    <span class="badge bg-success">Activo</span>
								    }
								    else
								    {
									    <span class="badge bg-danger">Inactivo</span>
								    }
								</td>
								<td>
									<div class="d-flex gap-2">
										<a type="button" class="btn btn-success btn-sm rounded-circle d-flex align-items-center justify-content-center"
										   style="width: 40px; height: 40px;" asp-action="View" asp-controller="Faculties" asp-route-id="@faculties.Id" title="Ver">
											<i class="fa-solid fa-eye"></i>
										</a>
										<a type="button" class="btn btn-warning btn-sm rounded-circle d-flex align-items-center justify-content-center"
										   style="width: 40px; height: 40px;" asp-action="UpSert" asp-controller="Faculties" asp-route-id="@faculties.Id" title="Editar">
											<i class="fa-solid fa-pencil"></i>
										</a>
										<a type="button" class="btn btn-danger btn-sm rounded-circle d-flex align-items-center justify-content-center"
										   style="width: 40px; height: 40px;" asp-action="Delete" asp-controller="Faculties" asp-route-id="@faculties.Id" title="Eliminar">
											<i class="fa-solid fa-trash"></i>
										</a>
									</div>
								</td>

							</tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Parcial1_DPWA/Views/Faculties/UpSert.cshtml
@model Faculties;

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="breadcrumb-item">
            <a asp-controller="Faculties" asp-action="Index">Index</a>
        </li>
        <li class="breadcrumb-item">Agregar un nuevo registro</li>
    </ol>
</nav>

<form asp-action="UpSert" asp-controller="Faculties" method="POST">
    <div asp-validation-summary="All" class="alert alert-danger">
        <i class="bi bi-exclamation-triangle-fill"></i>
    </div>
    <input type="hidden" asp-for="Id" value="@Model.Id" placeholder="Id" aria-label="Id">


    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-university"></i></span>
        <input type="text" class="form-control" asp-for="Name" placeholder="Name" aria-label="Nombre">
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-envelope"></i></span>
        <input type="text" class="form-control" asp-for="Correo" placeholder="Correo" aria-label="Correo">
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-file-lines"></i></span>
        <input type="text" class="form-control" asp-for="Description" placeholder="Description" aria-label="Descripccion">
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-hashtag"></i></span>
        <input type="number" class="form-control" asp-for="CantidadCarreras" value="@((Model.CantidadCarreras == 0) ? string.Empty : Model.CantidadCarreras)" placeholder="Cantidad de Carreras" aria-label="CantidadCarreras">
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-user"></i></span>
        <input type="text" class="form-control" asp-for="CreatedBy" placeholder="Creado por" aria-label="CreatedBy">
    </div>
    <button class="btn btn-success" type="submit"><span class="fas fade save"></span>Guardar Informacion</button>
</form>

Parcial1_DPWA/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Parcial1_DPWA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Parcial1_DPWA</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Parcial1_DPWA.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Parcial1_DPWA</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Faculties" asp-action="Index">Facultades</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Parcial1_DPWA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>